# Generated by Django 4.1.7 on 2024-01-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_post_comment_post_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postId',
            field=models.TextField(default='null'),
        ),
    ]
